### ISSUE TITLE
Bug: Database is not found with server address `postgres:5433` during ceremony

### ISSUE THREAD

**Issue by mayaCostantini** [repository-service-tuf/repository-service-tuf-worker#347]
### What happened?

When bootstrapping RSTUF after completing the ceremony, the corresponding file fails with the following error:

```
{
  "data": {
    "task_id": "5700be54fefc470eac8649d2bbf01859",
    "state": "FAILURE",
    "result": "<class 'sqlalchemy.exc.OperationalError'>(['(psycopg2.OperationalError) could not connect to server: Connection timed out\\n\\tIs the server running on host \"postgres\" (10.110.223.61) and accepting\\n\\tTCP/IP connections on port 5433?\\n'])"
  },
  "message": "Task state."
}
```

RSTUF is deployed with the kubernetes manifest provided in the [deployment guide](https://repository-service-tuf.readthedocs.io/en/stable/guide/deployment/guide/kubernetes.html) with value `postgres:5433` for `RSTUF_SQL_SERVER`.

The worker pod logs show the following log on container start up:

```
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/repository-service-tuf-worker/alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "/opt/repository-service-tuf-worker/alembic/env.py", line 63, in run_migrations_online
    connectable = engine_from_config(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 804, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    u = _url.make_url(url)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 838, in make_url
    return _parse_url(name_or_url)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 898, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string 'postgres:5433'
```

that indicate that the value cannot be parser correctly.

### What steps did you take?

- Deploy RSTUF with the provided kubernetes manifests
- Start the ceremony and bootstrap

### What behavior did you expect?

The postgres database is found during the bootstrap step and the value for the SQL server can be parsed correctly by the workers.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Hi @mayaCostantini,

Can you share the container image versions?

If possible, can you share the manifest for deployment (rstuf containers)

**Comment by mayaCostantini** [comment]
Sure, the image versions are:
-  `ghcr.io/repository-service-tuf/repository-service-tuf-worker@sha256:bd06d11d99a479a4c46e0298954a8109dfb948871b42f52fa192f9f4bdfeb26d`
- `ghcr.io/repository-service-tuf/repository-service-tuf-api@sha256:1fe891f7a67f7ddc78b0c3b74a78dc7c03b279e5481615bc28d0ec0e82ad69fa`

and the `deployments.yaml`:

```
# Redis deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: redis:4.0
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
status: {}
---
# Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespassword
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/rstuf
          image: postgres:15.1
          name: postgres
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
---
# http deployment (Web Server to expose metadata public)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-metadata
  labels:
    io.kompose.service: web-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-metadata
  template:
    metadata:
      labels:
        io.kompose.service: web-metadata
    spec:
      containers:
        - name: web-metadata
          image: httpd
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: rstuf-storage
      restartPolicy: Always
      volumes:
        - name: rstuf-storage
          persistentVolumeClaim:
            claimName: rstuf-storage
---
# RSTUF Worker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rstuf-worker
  name: rstuf-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: rstuf-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: rstuf-worker
    spec:
      containers:
        - env:
            - name: RSTUF_BROKER_SERVER
              value: redis://redis
            - name: RSTUF_REDIS_SERVER
              value: redis://redis
            - name: RSTUF_SQL_SERVER
              value: postgres:5433
            - name: RSTUF_SQL_USER
              value: postgres
            - name: RSTUF_SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespassword
                  key: password
            - name: RSTUF_KEYVAULT_BACKEND
              value: LocalKeyVault
            - name: RSTUF_LOCAL_KEYVAULT_PATH
              value: /var/opt/repository-service-tuf/keystorage/
            - name: RSTUF_LOCAL_KEYVAULT_KEYS
              valueFrom:
                secretKeyRef:
                  name: onlinekey
                  key: keys
            - name: RSTUF_STORAGE_BACKEND
              value: LocalStorage
            - name: RSTUF_LOCAL_STORAGE_BACKEND_PATH
              value: /var/opt/repository-service-tuf/storage
          image: ghcr.io/repository-service-tuf/repository-service-tuf-worker:latest
          name: rstuf-worker
          resources: {}
          tty: true
          volumeMounts:
            - name: onlinekey
              mountPath: "/run/secrets/onlinekey"
              readOnly: true
            - name: postgrespassword
              mountPath: "/run/secrets/postgrespassword"
              readOnly: true
            - mountPath: /var/opt/repository-service-tuf/storage
              name: rstuf-storage
            - mountPath: /var/opt/repository-service-tuf/keystorage
              name: rstuf-keystorage
      restartPolicy: Always
      volumes:
        - name: rstuf-storage
          persistentVolumeClaim:
            claimName: rstuf-storage
        - name: rstuf-keystorage
          persistentVolumeClaim:
            claimName: rstuf-keystorage
        - name: onlinekey
          secret:
            secretName: onlinekey
        - name: postgrespassword
          secret:
            secretName: postgrespassword
status: {}
---
# RSTUF API deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rstuf-api
  name: rstuf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rstuf-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: rstuf-api
    spec:
      containers:
        - env:
            - name: RSTUF_BROKER_SERVER
              value: redis://redis
            - name: RSTUF_REDIS_SERVER
              value: redis://redis
            - name: RSTUF_AUTH
              value: "true"
            - name: SECRETS_RSTUF_TOKEN_KEY
              value: somesecret
            - name: SECRETS_RSTUF_ADMIN_PASSWORD
              value: somepassword
          image: ghcr.io/repository-service-tuf/repository-service-tuf-api:latest
          name: rstuf-api
          ports:
            - containerPort: 80
          resources: {}
      volumes:
      restartPolicy: Always
status: {}
```
